<?xml version="1.0" encoding="UTF-8"?>
<!-- You may freely edit this file. See commented blocks below for -->
<!-- some examples of how to customize the build. -->
<!-- (If you delete it and reopen the project it will be recreated.) -->
<!-- By default, only the Clean and Build commands use this build script. -->
<!-- Commands such as Run, Debug, and Test only use this build script if -->
<!-- the Compile on Save feature is turned off for the project. -->
<!-- You can turn off the Compile on Save (or Deploy on Save) setting -->
<!-- in the project's Project Properties dialog box.-->
<project name="TestPDF" default="default" basedir=".">
    <description>Builds, tests, and runs the project TestPDF.</description>
    <import file="nbproject/build-impl.xml"/>
   <property name="version.num" value="2.0.6"/>
    <!-- <target name="-post-jar"> -->
        <!-- <property name="proguard.jar.path" value="D:\\Source_code\\Obfuscators\\progaurd\\proguard.jar" /> -->
        <!-- <property name="java.home.path" value="C:\\Program Files\\Java\\jdk1.8.0_202" /> -->
        
        <!-- <taskdef resource="proguard/ant/task.properties" -->
                 <!-- classpath="${proguard.jar.path}" /> -->
        
        <!-- <echo message="Obfuscating ${dist.jar}..."/> -->
        <!-- <mkdir dir="${build.dir}/obfuscated"/> -->
        <!-- <proguard printmapping="${build.dir}/obfuscated/${application.title}.map" renamesourcefileattribute="SourceFile" ignorewarnings="true"> -->

            <!-- <injar  file="${dist.jar}" /> -->
            <!-- <outjar file="${build.dir}/obfuscated/${application.title}.jar" /> -->

            <!-- <libraryjar path="${javac.classpath}" />           -->
            <!-- <libraryjar file="${java.home}/lib/rt.jar" /> -->
            <!-- <libraryjar file="${java.home}/lib/jce.jar" /> -->

            <!-- <keepattribute name="InnerClasses" /> -->
            <!-- <keepattribute name="SourceFile" /> -->
            <!-- <keepattribute name="LineNumberTable" /> -->
            <!-- <keepattribute name="Deprecated" /> -->
            <!-- <keepattribute name="*Annotation*" /> -->
            <!-- <keepattribute name="Signature" /> -->
            <!-- <keepattribute name="Exceptions" /> -->
            <!-- <keepattribute name="ConstantValue" /> -->

            <!-- <keep access="public"> -->
                <!-- <field  access="public protected" /> -->
                <!-- <method access="public protected" /> -->
            <!-- </keep>         -->

            <!-- <keepclassmembernames access="public"> -->
                <!-- <method type      ="java.lang.Class" -->
                        <!-- name      ="class$" -->
                        <!-- parameters="java.lang.String" /> -->
                <!-- <method type      ="java.lang.Class" -->
                        <!-- name      ="class$" -->
                        <!-- parameters="java.lang.String,boolean" /> -->
            <!-- </keepclassmembernames> -->

            <!-- <keepclasseswithmembernames> -->
                <!-- <method access="native" /> -->
            <!-- </keepclasseswithmembernames> -->

            <!-- <keepclassmembers extends="java.lang.Enum"> -->
                <!-- <method access="public static" -->
                        <!-- type="**[]" -->
                        <!-- name="values" -->
                        <!-- parameters="" /> -->
                <!-- <method access="public static" -->
                        <!-- type="**" -->
                        <!-- name="valueOf" -->
                        <!-- parameters="java.lang.String" /> -->
            <!-- </keepclassmembers> -->

            <!-- <keepnames implements="java.io.Serializable"/> -->
            <!-- <keepclassmembers implements="java.io.Serializable"> -->
                <!-- <field  access    ="final" -->
                        <!-- type      ="long" -->
                        <!-- name      ="serialVersionUID" /> -->
                <!-- <field  access    ="!static !transient" -->
                        <!-- name      ="**"/> -->
                <!-- <field  access    ="!private" -->
                        <!-- name      ="**"/> -->
                <!-- <method access    ="!private" -->
                        <!-- name      ="**"/> -->
                <!-- <method access    ="private" -->
                        <!-- type      ="void" -->
                        <!-- name      ="writeObject" -->
                        <!-- parameters="java.io.ObjectOutputStream" /> -->
                <!-- <method access    ="private" -->
                        <!-- type      ="void" -->
                        <!-- name      ="readObject" -->
                        <!-- parameters="java.io.ObjectOutputStream" /> -->
                <!-- <method type      ="java.lang.Object" -->
                        <!-- name      ="writeReplace" -->
                        <!-- parameters="" /> -->
                <!-- <method type      ="java.lang.Object" -->
                        <!-- name      ="readResolve" -->
                        <!-- parameters="" /> -->
            <!-- </keepclassmembers> -->

        <!-- </proguard> -->
        <!-- <copy file="${build.dir}/obfuscated/${application.title}.jar" tofile="${dist.dir}/${application.title}-${version.num}.jar" overwrite="true"/> -->
        <!-- <delete dir="${dist.jar}"/> -->
        <!-- <delete dir="${build.dir}/obfuscated"/> -->
    <!-- </target> -->
	<target name="-javadoc-build">
		<echo message="Skipping Javadoc generation."/>
    </target>
</project>
